name: github pages

on:
  push:
    branches:
      - master
      # - dev

jobs:
  deploy:
    runs-on: ubuntu-latest
    # concurrency:
    #   group: ${{ github.workflow }}-${{ github.ref }}
    steps:
      - name: Checkout Hugo repo
        uses: actions/checkout@v2
        with:
          # token: ${{ secrets.ACCESS_TOKEN }}
          submodules: recursive # Fetch Hugo themes (true OR recursive)
          fetch-depth: 0 # Fetch all history for .GitInfo and .Lastmod

      # - name: Checkout Blog repo
      #   uses: actions/checkout@v3
      #   with:
      #     repository: real-jacket/real-jacket.github.io
      #     path: public
      #     token: ${{ secrets.ACCESS_TOKEN }}

      - name: Setup Hugo
        uses: peaceiris/actions-hugo@v2
        with:
          hugo-version: latest
          extended: true

      - name: Restore file modification time
        run: |
          find content/posts/**/* -name '*.md' | while read file; do touch -d "$(git log -1 --format="@%ct" "$file")" "$file"; done

      - name: Build
        run: hugo -v --gc --minify

      - name: Deploy
        uses: peaceiris/actions-gh-pages@v3
        with:
          personal_token: ${{ secrets.ACCESS_TOKEN }}
          external_repository: real-jacket/real-jacket.github.io
          publish_branch: master
          publish_dir: ./public

      - name: Push search json
        env:
          ALGOLIA_APP_ID: ${{ secrets.ALGOLIA_APP_ID }}
          ALGOLIA_ADMIN_KEY: ${{ secrets.ALGOLIA_ADMIN_KEY }}
          ALGOLIA_INDEX_NAME: ${{ secrets.ALGOLIA_INDEX_NAME }}
          ALGOLIA_INDEX_FILE: ${{ secrets.ALGOLIA_INDEX_FILE }}
        run: |
          npm install
          npm run algolia
