name: github pages

on:
  push:
    branches:
      - master

jobs:
  deploy:
    runs-on: ubuntu-20.04
    concurrency:
      group: ${{ github.workflow }}-${{ github.ref }}
    steps:
      - name: Checkout Hugo repo
        uses: actions/checkout@v3
        with:
          token: ${{ secrets.ACCESS_TOKEN }}
          submodules: true # Fetch Hugo themes (true OR recursive)
          fetch-depth: 0 # Fetch all history for .GitInfo and .Lastmod

      - name: Checkout Blog repo
        uses: actions/checkout@v3
        with:
          repository: real-jacket/real-jacket.github.io
          path: public
          token: ${{ secrets.ACCESS_TOKEN }}

      - name: Setup Hugo
        uses: peaceiris/actions-hugo@v2
        with:
          hugo-version: "0.74.2"
          extended: true

      - name: Build
        run: hugo --minify

      - name: Deploy
        run: |
          cd ./public
          if [ -n "$(git status -s)" ];then
              git config --local user.email "action@github.com"
              git config --local user.name "GitHub Action"
              git add .
              msg="rebuilding site $(date)"
              if [ -n "$*" ]; then
                msg="$*"
              fi
              git commit -m "$msg"
              git push origin master
          fi

      - name: Push search json
        env:
          ALGOLIA_APP_ID: ${{ secrets.ALGOLIA_APP_ID }}
          ALGOLIA_ADMIN_KEY: ${{ secrets.ALGOLIA_ADMIN_KEY }}
          ALGOLIA_INDEX_NAME: ${{ secrets.ALGOLIA_INDEX_NAME }}
          ALGOLIA_INDEX_FILE: ${{ secrets.ALGOLIA_INDEX_FILE }}
        run: |
          npm install
          npm run algolia
