name: github pages

on:
  push:
    branches:
      - master

jobs:
  deploy:
    runs-on: ubuntu-18.04
    steps:
      - uses: actions/checkout@v2
        with:
          token: ${{ secrets.ACCESS_TOKEN }}
          submodules: true # Fetch Hugo themes (true OR recursive)
          fetch-depth: 0 # Fetch all history for .GitInfo and .Lastmod

      - name: Setup Hugo
        uses: peaceiris/actions-hugo@v2
        with:
          hugo-version: "0.74.2"
          extended: true

      - name: Build and deploy
        run: hugo --minify

      - uses: actions/checkout@v2
        with:
          token: ${{ secrets.ACCESS_TOKEN }}
          # submodules: true # Fetch Hugo themes (true OR recursive)
          # fetch-depth: 0 # Fetch all history for .GitInfo and .Lastmod

      - name: Deploy
        run: |
          chmod +x deploy.sh
          ./deploy.sh

      - name: Push search json
        env:
          ALGOLIA_APP_ID: ${{ secrets.ALGOLIA_APP_ID }}
          ALGOLIA_ADMIN_KEY: ${{ secrets.ALGOLIA_ADMIN_KEY }}
          ALGOLIA_INDEX_NAME: ${{ secrets.ALGOLIA_INDEX_NAME }}
          ALGOLIA_INDEX_FILE: ${{ secrets.ALGOLIA_INDEX_FILE }}
        run: |
          npm install
          npm run algolia
      # - name: Checkout public
      #   uses: actions/checkout@v2
      #   with:
      #     repository: real-jacket/real-jacket.github.io
      #     token: ${{ secrets.ACCESS_TOKEN }}
      #     path: public
      # - name: Deploy
      #   run: |
      #     cd ./public
      #     git add .
      #     msg="rebuilding site $(date)"
      #     if [ -n "$*" ]; then
      #       msg="$*"
      #     fi
      #     git commit -m "$msg"
      #     git push origin master
